### ISSUE TITLE
Many to many relationships not working

### ISSUE THREAD

**Issue by miketrumpf** [miketrumpf/whos_up#14]
Context
User story - I want to have many posts so my friends can see what I'm up for.  I want to be able to join my friend's posts so they know that I am interested in what they are up for.

When a user creates a post it is not linking them together in my join table.
They contain all relevant data in their respective tables.

Below is a user migration and model and a single type of post migration and model. My app is using facebook's login, so I am using a user's unique facebook id as the primary key.  

User MIGRATION

``` js
"use strict";

module.exports = {
  up: function(migration, DataTypes, done) {
    migration.createTable("users", {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: false,
        type: DataTypes.INTEGER
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false
      },
      facebook_id: {
        type: DataTypes.STRING,
        primaryKey: true,
        allowNull: false,
        unique: true
      },
      picture: {
        type: DataTypes.STRING
      },
      created_at: {
        type: DataTypes.DATE,
        allowNull: false
      },
      updated_at: {
        type: DataTypes.DATE,
        allowNull: false
      }
    }).done(done);
  },

  down: function(migration, DataTypes, done) {
    migration.dropTable("users").done(done);
  }
};
```

USER MODEL

``` js
"use strict";
module.exports = function(sequelize, DataTypes) {
  var users = sequelize.define("users", {
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    facebook_id: {
      type: DataTypes.STRING,
      allowNull: false
      },
      picture: {
        type: DataTypes.STRING,
      }
    }, {
      underscored: true,

      classMethods: {

        associate: function(models) {
          users.belongsToMany(models.fun_posts, {
            through: "funPosts_users",
            foreignKey: "user_facebook_id"
          });
          users.belongsToMany(models.food_posts, {
            through: "foodPosts_users",
            foreignKey: "user_facebook_id"
          });
          users.belongsToMany(models.discussion_posts, {
            through:"discussionPosts_users",
            foreignKey: "user_facebook_id"
          });
        }
      }
    });
    return users;
};
```

FUN POST MIGRATION

``` js
"use strict";

module.exports = {
  up: function(migration, DataTypes, done) {
    migration.createTable("fun_posts", {
      id: {
        type: DataTypes.INTEGER,
        allowNull: false,
        autoIncrement: true,
        primaryKey: true
      },
      user_name: {
        type: DataTypes.STRING,
        allowNull: false
      },
      genre: {
        type: DataTypes.STRING,
        allowNull: false
      },
      title: {
        type: DataTypes.STRING,
        allowNull: false
      },
      content: {
        type: DataTypes.STRING,
        allowNull: false
      },
      start_date: {
        type: DataTypes.DATE,
        allowNull: false
      },
      exp_date: {
        type: DataTypes.DATE,
        allowNull: false
      },
      facebook_id: {
        type: DataTypes.STRING,
        allowNull: false
      },
      created_at: {
        type: DataTypes.DATE,
        allowNull: false
      },
      updated_at: {
        type: DataTypes.DATE,
        allowNull: false
      }
    }).done(done);
  },

  down: function(migration, DataTypes, done) {
    migration.dropTable("fun_posts").done(done);
  }
};
```

FUN POSTS MODEL

``` js
"use strict";
module.exports = function(sequelize, DataTypes) {
  var fun_posts = sequelize.define("fun_posts", {
    user_name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false
    },
    genre: {
      type: DataTypes.STRING,
      allowNull: false
    },
    content: {
      type: DataTypes.STRING,
      allowNull: false
    },
    start_date: {
      type: DataTypes.DATE,
      allowNull: false,
      validate: {
        isDate: {msg: "must be a valid date"},
        isAfter: {args: ["4/17/2015"], msg: "Can not be in the past"}
      }
    },
    exp_date: {
      type: DataTypes.DATE,
      allowNull: false,
      validate: {
        isDate:{msg: "must be a valid date"},
        isAfter: {args:["4/17/2015"], msg: "Can not be in the past"}
      }
    },
    facebook_id: {
      type: DataTypes.STRING,
      allowNull: false
    }
  },
  {
    underscored: true,

    classMethods: {
      associate: function(models){
        fun_posts.belongsToMany(models.users, {
          through: "funPosts_users",
          foreignKey: "fun_post_id"
        });
      }
    }
  });
  return fun_posts
};
```

I tried checking all of my syntax diligently.  I have been trying to use the venu app as a model since there was a many to many relationship between artists and events.  I am confused and frustrated

**Comment by harimohanraj89** [comment]
Hey Mike, couple of things.
- Mention us in the body of your issue, else we will not all see this. I happened to stumble upon it in my GitHub news feed.
- What is going wrong? Are you receiving errors? If so, when are you receiving errors? What route on your server? What front-end code is hitting your server to cause this? If there are no errors, what expected behavior is not occurring? Are entries not being created in your join table between fun posts and users?

**Comment by miketrumpf** [comment]
@harimohanraj89 
Oh wow I thought if I just had you as collaborators you would automatically be notified.  
Ok, I am not seeing any explicit errors.  
When someone submits a post it is hitting this function in my view

``` js
submitPost: function() {
    console.log("submit post button clicked");
    var type = $("#create-type").val();
    var title = $("#create-title").val();
    var genre = $("#create-genre").val();
    var content = $("#create-content").val();
    var startDate = $("#create-start-date").val();
    var expDate   = $("#create-exp-date").val();
    var facebookId = App.user.attributes.facebook_id;
    var picture    = App.user.attributes.picture;
    var user_name   = App.user.attributes.name;
    var postModel = ({title: title, genre: genre, content: content, start_date: startDate , exp_date: expDate, facebook_id: facebookId, user_name: user_name})


    if (type === "fun" || type ==="Fun") {
      App.fun_post.save(postModel)
      App.fun_posts.fetch();
      alert("fun post created")

    } else if (type === "food"|| type === "Food") {

      App.food_post.save(postModel)
      alert("food post created")

    } else {
      App.discussion_post.save(postModel)
      alert("discussion post created")
    }
  },
```

IT GOES TO MY FUN_POSTROUTER AND HITS THIS URL

``` js
fun_postRouter.post("/", function (req, res) {
var title = req.body.title;
var content = req.body.content;
var genre = req.body.genre;
var start_date = req.body.start_date;
var exp_date   = req.body.exp_date;
var facebook_id = req.body.facebook_id;
var user_name   = req.body.user_name;
  FunPost.create({
    title: title,
    content: content,
    genre: genre,
    start_date: start_date,
    exp_date: exp_date,
    facebook_id: facebook_id,
    user_name: user_name
  })
    .then(function(newPost) {
      res.send(newPost)
    })
});
```

IT CREATES THE POST SUCCESSFULLY, BUT THERE IS NO ENTRY INTO MY JOIN TABLE

**Comment by miketrumpf** [comment]
@bigtone1284 @WilliamfShaw

**Comment by DrRobotmck** [comment]
- Where do you create the relationship between a user and a fun_post?
- What branch are you working on?

**Comment by miketrumpf** [comment]
@DrRobotmck
Isn't that relationship created in the classMethods Associations?

So in the user model I have this classMethod

``` js
  classMethods: {

    associate: function(models) {
      users.belongsToMany(models.fun_posts, {
        through: "funPosts_users",
        foreignKey: "user_facebook_id"
      });
      users.belongsToMany(models.food_posts, {
        through: "foodPosts_users",
        foreignKey: "user_facebook_id"
      });
      users.belongsToMany(models.discussion_posts, {
        through:"discussionPosts_users",
        foreignKey: "user_facebook_id"
      });
    }
  }
});
return users;
```

And in the fun_post model I have

``` js
classMethods: {
  associate: function(models){
    fun_posts.belongsToMany(models.users, {
      through: "funPosts_users",
      foreignKey: "fun_post_id"
    });
  }
}
```

**Comment by harimohanraj89** [comment]
Venü is not a good example of setting up many to many relationships since, even though our database was designed to capture such a relationship, the code itself did not form any relationships between events and artists. That app was merely an example to practice class and instance methods. Take a look at this version of `bloggr` that had a many-to-many relationship between tags and posts. In particular, pay special attention to the work we have to put into our server to _take advantage_ of the association we have set up to relate a _specific post to a specific tag_.

https://github.com/ga-students/WDI_McClane/blob/master/w06/d01/INSTRUCTOR/bloggr_app_solution/server.js#L169

**Comment by miketrumpf** [comment]
@harimohanraj89 
Ok so I have to hit a route that looks something like 
userRouter.post("/:id/fun_posts"....
 I think I know how to hit that url using an ajax call, but am I supposed to do it using a backbone method?

**Comment by miketrumpf** [comment]
@harimohanraj89 
Hi Hari, I created this route
userRouter.post("/:facebook_id/fun_posts", function (req, res) {
var title = req.body.title;
var content = req.body.content;
var genre = req.body.genre;
var start_date = req.body.start_date;
var exp_date   = req.body.exp_date;
var facebook_id = req.body.facebook_id;
var user_name   = req.body.user_name;

  User
    .findOne({
      where: {facebook_id: req.params.facebook_id}
    })
    .then(function(user) {
      FunPost
        .create({
        title: title,
        content: content,
        genre: genre,
        start_date: start_date,
        exp_date: exp_date,
        facebook_id: facebook_id,
        user_name: user_name
        })
          .then(function(newPost) {
            res.send(newPost)
          })
    })
})
I AM HITTING IT IN THIS FUNCTION WITH THIS AJAX REQUEST
submitPost: function() {
    console.log("submit post button clicked");
    var type = $("#create-type").val();
    var title = $("#create-title").val();
    var genre = $("#create-genre").val();
    var content = $("#create-content").val();
    var startDate = $("#create-start-date").val();
    var expDate   = $("#create-exp-date").val();
    var facebookId = App.user.attributes.facebook_id;
    var picture    = App.user.attributes.picture;
    var user_name   = App.user.attributes.name;
    var postModel = ({title: title, genre: genre, content: content, start_date: startDate , exp_date: expDate, facebook_id: facebookId, user_name: user_name})

```
debugger
if (type === "fun" || type ==="Fun") {
  debugger
  $.ajax({
    url: "/users/" + facebookId + "/fun_posts",
    method: "POST",
    data: {
      title: title,
      genre: genre,
      content: content,
      start_date: startDate,
      exp_date: expDate,
      facebook_id: facebookId,
      user_name: user_name
    }
  }).done(App.fun_posts.fetch());
```

AND I AM SEEING THIS MESSAGE IN MY TERMINAL
terminal message 
POST /users/845636625427/fun_posts 200 118.591 ms - 283
It is still somehow saving the post to fun_posts, but nothing on the join table.

**Comment by miketrumpf** [comment]
@harimohanraj89 
I am looking at the bloggr app solution and there is something in this route that I don't really understand

// Create
app.post('/users/:id/posts', function(req, res) {
  var userId = req.params.id;
  var postParams = req.body;

  User
    .findOne(userId)
    .then(function(user) {
      Post
        .create(postParams)
        .then(function(newPost) {

---

```
      user.addPost(newPost) 
```

 HOW ARE WE ABLE TO CALL addPost HERE?  I think this is the piece that I am missing, but when I try to add my post counterpart addFunPost, it tells me undefined is not a function

---

```
      res.send(newPost);
    });
});
```

});

**Comment by harimohanraj89** [comment]
Closing, after we figured out that we need to set a custom field to be the primary key in the **model** file as well as the migration.

**Comment by miketrumpf** [comment]
@harimohanraj89 
You are the man! Thanks again!
