### ISSUE TITLE
Stuck on getting post router to only send through active (non expired) posts 

### ISSUE THREAD

**Issue by miketrumpf** [miketrumpf/whos_up#15]
@harimohanraj89 @DrRobotmck @bigtone1284 @WilliamfShaw 
User story- I don't want to see posts from events that have already expired.

I am trying to change my getPosts route to filter through the posts and only send back posts that are not expired.  This is what i have so far.

fun_postRouter.get("/", function (req, res) {
var livePosts = [];
var today = new Date();
  FunPost.findAll()
    .then(function(posts) {
      posts.forEach(function(post) {
        console.log("post is" + post)
        console.log("post.exp_date is " + post.exp_date)
        console.log("post.id is " + post.id)
        if(post.exp_date > today) {
          livePosts.push(post)
        } 
        else { 
        }
      })
      console.log("live Posts is"  + livePosts)
      FunPost.findAll({  ------this is where the trouble starts
        where: {
          id: {  
            $in: livePosts
          }
        }
      }).then(function(posts) {
         res.send(posts)
       });

```
});
```

});

I console logged everything and the array is created.  I am just getting errors on the last step where I am calling findAll again and trying to specifically get the ones in my livePosts array.  The exact error I receive is Possibly unhandled Error: Cannot find module 'pg-native'.  I looked that up and it has something to do with something trying to clone the pg module, invoking the native property.  I don't really know what it means.  I feel like I am very close though.  I am also on the sequelize docs trying to find the solution for the last step of this route.

**Comment by bigtone1284** [comment]
@harimohanraj89 @DrRobotmck @WilliamfShaw @miketrumpf  taken.
